name: build-deploy-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes
#  
#  using spn-auth with Client ID and Tenant ID for environemnet login 
#  
#  using secrets for
#   SP_CLIENTID           Service Principal App ID
#   SP_TENANTID           Service Principal Azure AD tenant
#   SP_SECRET             Service Principal secrtes
#   DevEnvironmentUrl     Url referencing the development environment


on:
  workflow_dispatch:
  push:
    branches:

env:
  solution_name: RegisterServiceEndpointsSolution
  solution_package_folder: deployment/packages/
  solution_source_folder: deployment/solutions/

jobs:
  deploy-to-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0.4.0
      with:
        environment-url: ${{secrets.DevEnvironmentUrl}}
        app-id: ${{secrets.SP_CLIENTID}}
        client-secret: ${{ secrets.SP_SECRET }}
        tenant-id: ${{secrets.SP_TENANTID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: ${{ env.solution_source_folder}}/${{ env.solution_name }}
        solution-file: ${{ env.solution_package_folder}}/${{ env.solution_name }}.zip
        solution-type: Managed

    - name: Import solution as Managed to build env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{secrets.DevEnvironmentUrl}}
        app-id: ${{secrets.SP_CLIENTID}}
        client-secret: ${{ secrets.SP_SECRET }}
        tenant-id: ${{secrets.SP_TENANTID}}
        solution-file: ${{ env.solution_package_folder}}/${{ env.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

  deploy-to-test:
    runs-on: windows-latest
    needs: deploy-to-dev
    env:
      RUNNER_DEBUG: 1
    
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0.4.0
      with:
        environment-url: ${{secrets.DevEnvironmentUrl}}
        app-id: ${{secrets.SP_CLIENTID}}
        client-secret: ${{ secrets.SP_SECRET }}
        tenant-id: ${{secrets.SP_TENANTID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: ${{ env.solution_source_folder}}/${{ env.solution_name }}
        solution-file: ${{ env.solution_package_folder}}/${{ env.solution_name }}.zip
        solution-type: Managed

    - name: Import solution as Managed to build env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{secrets.DevEnvironmentUrl}}
        app-id: ${{secrets.SP_CLIENTID}}
        client-secret: ${{ secrets.SP_SECRET }}
        tenant-id: ${{secrets.SP_TENANTID}}
        solution-file: ${{ env.solution_package_folder}}/${{ env.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

    # - name: export-solution action
    #   uses: microsoft/powerplatform-actions/export-solution@0.4.0
    #   with:
    #     environment-url: ${{secrets.DevEnvironmentUrl}}
    #     app-id: ${{secrets.SP_CLIENTID}}
    #     client-secret: ${{ secrets.SP_SECRET }}
    #     tenant-id: ${{secrets.SP_TENANTID}}
    #     solution-name: ${{ env.solution_name }}
    #     solution-output-file: ${{ env.solution_exported_folder}}/${{ env.solution_name }}.zip

    # - name: unpack-solution action
    #   uses: microsoft/powerplatform-actions/unpack-solution@0.4.0
    #   with:
    #     solution-file: ${{ env.solution_exported_folder}}/${{ env.solution_name }}.zip
    #     solution-folder: ${{ env.solution_folder}}/${{ env.solution_name }}
    #     solution-type: 'Unmanaged'
    #     overwrite-files: true

    # - name: branch-solution, prepare it for a PullRequest
    #   uses: microsoft/powerplatform-actions/branch-solution@v0
    #   with:
    #     solution-folder: ${{ env.solution_folder}}/${{ env.solution_name }}
    #     solution-target-folder: ${{ env.solution_target_folder}}/${{ env.solution_name }}
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     allow-empty-commit: true
